ai.blackthorn.chem-ai: # {group_id}.{name} from the knime.yml
  src: C:/work/DrugDiscovery/fluoricLogPpKa_KNIME_PYTHON_NODE/github_repository/fluoricLogPpKa_KNIME/knime_extension # Path to folder containing the extension files
  conda_env_path: C:/Users/38066/anaconda3/envs/knime_env # Path to the Python environment to use
  debug_mode: false # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform
